# Generated by Django 2.2.10 on 2020-03-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0005_trial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='trial',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='doorgame.Trial'),
        ),
    ]
