# Generated by Django 2.2.10 on 2020-03-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0006_choice_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
    ]
