# Generated by Django 2.2.10 on 2020-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0010_result_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='first_or_second_choice',
            field=models.IntegerField(default=0),
        ),
    ]
