# Generated by Django 2.2.10 on 2020-03-21 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0011_choice_first_or_second_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorygame',
            name='user',
        ),
        migrations.AddField(
            model_name='memorygame',
            name='trial',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='doorgame.Trial'),
        ),
    ]
