# Generated by Django 2.2.10 on 2020-03-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0012_auto_20200321_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygame',
            name='box_one',
            field=models.BooleanField(default=False),
        ),
    ]
