# Generated by Django 2.2.10 on 2020-03-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0013_memorygame_box_one'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorygame',
            old_name='box_one',
            new_name='box_1',
        ),
        migrations.AddField(
            model_name='memorygame',
            name='box_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorygame',
            name='box_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorygame',
            name='box_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorygame',
            name='box_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorygame',
            name='box_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorygame',
            name='box_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorygame',
            name='box_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorygame',
            name='box_9',
            field=models.BooleanField(default=False),
        ),
    ]
