# Generated by Django 2.2.10 on 2020-03-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0014_auto_20200321_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygame',
            name='initial_or_final',
            field=models.CharField(default='', max_length=15),
        ),
    ]
