# Generated by Django 2.2.10 on 2020-03-28 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doorgame', '0016_trial_number_of_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_stayed_lost', models.IntegerField(default=0)),
                ('estimate_stayed_won', models.IntegerField(default=0)),
                ('estimate_switched_lost', models.IntegerField(default=0)),
                ('estimate_switched_won', models.IntegerField(default=0)),
                ('familiar', models.TextField(default='blank')),
                ('gender', models.TextField(default='blank')),
                ('education_level', models.TextField(default='blank')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
