# Generated by Django 2.2.10 on 2020-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0017_surveyanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswers',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
