# Generated by Django 2.2.10 on 2020-04-05 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doorgame', '0020_auto_20200405_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygame',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
