# Generated by Django 2.2.10 on 2020-04-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0021_memorygame_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorygame',
            name='user',
        ),
    ]
