# Generated by Django 2.2.10 on 2020-04-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0023_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='memory_game_list_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='prelim_completed',
            field=models.BooleanField(default=False),
        ),
    ]
