# Generated by Django 2.2.10 on 2020-04-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0024_auto_20200412_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trials_completed',
            field=models.IntegerField(default=0),
        ),
    ]
