# Generated by Django 2.2.10 on 2021-02-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0025_profile_trials_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryGameHigh',
            fields=[
                ('memorygame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doorgame.MemoryGame')),
                ('box_10', models.BooleanField(default=False)),
                ('box_11', models.BooleanField(default=False)),
                ('box_12', models.BooleanField(default=False)),
                ('box_13', models.BooleanField(default=False)),
                ('box_14', models.BooleanField(default=False)),
                ('box_15', models.BooleanField(default=False)),
                ('box_16', models.BooleanField(default=False)),
            ],
            bases=('doorgame.memorygame',),
        ),
        migrations.AddField(
            model_name='profile',
            name='low_medium_or_high_dots_setting',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
