# Generated by Django 2.2.10 on 2021-03-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0026_auto_20210217_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswers',
            name='regret_value',
            field=models.IntegerField(default=0),
        ),
    ]
