# Generated by Django 2.2.10 on 2021-03-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0027_surveyanswers_regret_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='regret_forwards',
            field=models.BooleanField(default=True),
        ),
    ]
