# Generated by Django 2.2.10 on 2021-03-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorgame', '0028_profile_regret_forwards'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialPrelim',
            fields=[
                ('trial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doorgame.Trial')),
            ],
            bases=('doorgame.trial',),
        ),
        migrations.CreateModel(
            name='MemoryGameHighPrelim',
            fields=[
                ('memorygamehigh_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doorgame.MemoryGameHigh')),
                ('trial_prelim', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='doorgame.TrialPrelim')),
            ],
            bases=('doorgame.memorygamehigh',),
        ),
    ]
